[package]
name = "psistats_plugin_cpu"
version = "0.1.0"
authors = ["Alex Dow <adow@psikon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
name = "plugin_cpu"

[dependencies]
psistats_service = { path = "../../psistats_service" }
crossbeam-channel = "0.4.2"
lazy_static = "1.4.0"
sysinfo = { git = "https://github.com/GuillaumeGomez/sysinfo" }

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 16
panic = 'unwind'
incremental = true
overflow-checks = true

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = false
