[package]
name = "psistats_plugin_cpu"
version = "0.1.0"
authors = ["Alex Dow <adow@psikon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
psistats_service = { path = "../../psistats_service" }
toml = "0.5.6"

