[package]
name = "psistats_plugin_os"
version = "0.3.0-beta"
authors = ["Alex Dowgailenko <adow@psikon.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
name = "plugin_os"

[dependencies]
libpsistats = { path = "../../libpsistats" }
os_info = "3.3.0"
